apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "{{ .Values.kafka.brokers | default "kafka:9092" }}"
  - name: consumerGroup
    value: "{{ .Values.kafka.consumerGroup | default "dapr-consumer-group" }}"
  - name: authRequired
    value: "{{ .Values.kafka.authRequired | default "false" }}"
