apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evolution-of-todo.frontend.fullname" . }}
  labels:
    {{- include "evolution-of-todo.labels" . | nindent 4 }}
    app: evolution-of-todo-frontend
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evolution-of-todo.selectorLabels" . | nindent 6 }}
      app: evolution-of-todo-frontend
  template:
    metadata:
      {{- if .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml .Values.frontend.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evolution-of-todo.selectorLabels" . | nindent 8 }}
        app: evolution-of-todo-frontend
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry | default .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "evolution-of-todo.backend.fullname" . }}:{{ .Values.backend.service.port }}"
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}