apiVersion: v1
kind: Secret
metadata:
  name: neon-db-secret
type: Opaque
data:
  connectionString: {{ .Values.neonDb.connectionString | b64enc | quote }}
  username: {{ .Values.neonDb.username | b64enc | quote }}
  password: {{ .Values.neonDb.password | b64enc | quote }}
