apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evolution-of-todo.fullname" . }}-postgres
  labels:
    {{- include "evolution-of-todo.labels" . | nindent 4 }}
    app: evolution-of-todo-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "evolution-of-todo.selectorLabels" . | nindent 6 }}
      app: evolution-of-todo-postgres
  template:
    metadata:
      labels:
        {{- include "evolution-of-todo.selectorLabels" . | nindent 8 }}
        app: evolution-of-todo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "todo_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: neon-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neon-db-secret
                  key: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
