{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "evolution-of-todo.postgres.fullname" . }}
  labels:
    {{- include "evolution-of-todo.labels" . | nindent 4 }}
    app: evolution-of-todo-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "evolution-of-todo.selectorLabels" . | nindent 4 }}
    app: evolution-of-todo-postgres
{{- end }}